import { Product, GoldRate } from './types';

export const initialGoldRates: GoldRate[] = [
  { type: '24K Gold', price: 9850, change: 1.2,  unit: 'per 10g' },
  { type: '22K Gold', price: 9020, change: -0.8, unit: 'per 10g' },
  { type: '18K Gold', price: 7380, change: 0.6,  unit: 'per 10g' },
  { type: 'Silver',   price: 112,  change: 0.5,  unit: 'per 10g' },
  { type: 'Platinum', price: 3480, change: 2.1,  unit: 'per 10g' },
];

// NO PRICE, WEIGHT, OR PURITY FIELDS — customers enquire on WhatsApp
export const products: Product[] = [

  // ── CHAINS ─────────────────────────────────────────────────────────────────
  { id: 100, name: 'Classic Gold Chain',       category: 'Chains',    description: 'Everyday Wear Chain',         details: 'Classic 22K gold chain.',                     icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain.jpg') },
  { id: 101, name: 'Elegant Chain 1',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain1.jpg') },
  { id: 102, name: 'Elegant Chain 2',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain2.jpg') },
  { id: 103, name: 'Elegant Chain 3',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain3.jpg') },
  { id: 104, name: 'Elegant Chain 4',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain4.jpg') },
  { id: 105, name: 'Elegant Chain 5',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain5.jpg') },
  { id: 106, name: 'Elegant Chain 6',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain6.jpg') },
  { id: 107, name: 'Elegant Chain 7',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain7.jpg') },
  { id: 108, name: 'Elegant Chain 8',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain8.jpg') },
  { id: 109, name: 'Elegant Chain 9',          category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain9.jpg') },
  { id: 110, name: 'Elegant Chain 10',         category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain10.jpg') },
  { id: 111, name: 'Elegant Chain 11',         category: 'Chains',    description: 'Traditional Gold Chain',      details: 'Beautiful link design in 22K gold.',          icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/chain11.jpg') },

  // ── LADIES RINGS ─────────────────────────────────────────────────────────────
  { id: 201, name: 'Ladies Ring 1',            category: 'Rings',     description: 'Classic Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring1.jpg') },
  { id: 202, name: 'Ladies Ring 2',            category: 'Rings',     description: 'Designer Ladies Ring',        details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring2.jpg') },
  { id: 203, name: 'Ladies Ring 3',            category: 'Rings',     description: 'Floral Ladies Ring',          details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring3.jpg') },
  { id: 204, name: 'Ladies Ring 4',            category: 'Rings',     description: 'Lightweight Ladies Ring',     details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring4.jpg') },
  { id: 205, name: 'Ladies Ring 5',            category: 'Rings',     description: 'Premium Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring5.jpg') },
  { id: 206, name: 'Ladies Ring 6',            category: 'Rings',     description: 'Classic Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring6.jpg') },
  { id: 207, name: 'Ladies Ring 7',            category: 'Rings',     description: 'Statement Ladies Ring',       details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring7.jpg') },
  { id: 208, name: 'Ladies Ring 8',            category: 'Rings',     description: 'Designer Ladies Ring',        details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring8.jpg') },
  { id: 209, name: 'Ladies Ring 9',            category: 'Rings',     description: 'Minimalist Ladies Ring',      details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring9.jpg') },
  { id: 210, name: 'Ladies Ring 10',           category: 'Rings',     description: 'Classic Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring10.jpg') },
  { id: 211, name: 'Ladies Ring 11',           category: 'Rings',     description: 'Floral Ladies Ring',          details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring11.jpg') },
  { id: 212, name: 'Ladies Ring 12',           category: 'Rings',     description: 'Premium Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring12.jpg') },
  { id: 213, name: 'Ladies Ring 13',           category: 'Rings',     description: 'Designer Ladies Ring',        details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring13.jpg') },
  { id: 214, name: 'Ladies Ring 14',           category: 'Rings',     description: 'Statement Ladies Ring',       details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring14.jpg') },
  { id: 215, name: 'Ladies Ring 15',           category: 'Rings',     description: 'Lightweight Ladies Ring',     details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring15.jpg') },
  { id: 216, name: 'Ladies Ring 16',           category: 'Rings',     description: 'Classic Ladies Ring',         details: 'Elegant everyday ring for women.',            icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/ladies ring16.jpg') },

  // ── GENTS RINGS ──────────────────────────────────────────────────────────────
  { id: 301, name: 'Gents Solid Ring 1',       category: 'Rings',     description: 'Classic Men\'s Ring',         details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring1.jpg') },
  { id: 302, name: 'Gents Solid Ring 2',       category: 'Rings',     description: 'Bold Men\'s Ring',            details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring2.jpg') },
  { id: 303, name: 'Gents Solid Ring 3',       category: 'Rings',     description: 'Heavy Men\'s Ring',           details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring3.jpg') },
  { id: 304, name: 'Gents Solid Ring 4',       category: 'Rings',     description: 'Classic Men\'s Ring',         details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring4.jpg') },
  { id: 305, name: 'Gents Solid Ring 5',       category: 'Rings',     description: 'Designer Men\'s Ring',        details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring5.jpg') },
  { id: 306, name: 'Gents Solid Ring 6',       category: 'Rings',     description: 'Statement Men\'s Ring',       details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring6.jpg') },
  { id: 307, name: 'Gents Solid Ring 7',       category: 'Rings',     description: 'Bold Men\'s Ring',            details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring7.jpg') },
  { id: 308, name: 'Gents Solid Ring 8',       category: 'Rings',     description: 'Classic Men\'s Ring',         details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring8.jpg') },
  { id: 309, name: 'Gents Solid Ring 9',       category: 'Rings',     description: 'Designer Men\'s Ring',        details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring9.jpg') },
  { id: 310, name: 'Gents Solid Ring 10',      category: 'Rings',     description: 'Heavy Men\'s Ring',           details: 'Solid build 22K gold ring for men.',          icon: 'diamond-outline', color: '#8C5C2D', image: require('../assets/gents ring10.jpg') },

  // ── PENDANT SETS ─────────────────────────────────────────────────────────────
  { id: 401, name: 'Gold Pendant Set 1',       category: 'Pendants',  description: 'Designer Pendant Set',        details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set1.jpg') },
  { id: 402, name: 'Gold Pendant Set 2',       category: 'Pendants',  description: 'Bridal Pendant Set',          details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set2.jpg') },
  { id: 403, name: 'Gold Pendant Set 3',       category: 'Pendants',  description: 'Classic Pendant Set',         details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set3.jpg') },
  { id: 404, name: 'Gold Pendant Set 4',       category: 'Pendants',  description: 'Floral Pendant Set',          details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set4.jpg') },
  { id: 405, name: 'Gold Pendant Set 5',       category: 'Pendants',  description: 'Designer Pendant Set',        details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set5.jpg') },
  { id: 406, name: 'Gold Pendant Set 6',       category: 'Pendants',  description: 'Heavy Pendant Set',           details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set6.jpg') },
  { id: 407, name: 'Gold Pendant Set 7',       category: 'Pendants',  description: 'Classic Pendant Set',         details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set7.jpg') },
  { id: 408, name: 'Gold Pendant Set 8',       category: 'Pendants',  description: 'Bridal Pendant Set',          details: 'Matching pendant and earrings set.',          icon: 'star-outline',    color: '#8C5C2D', image: require('../assets/pandent set8.jpg') },

  // ── LONG HAAR ────────────────────────────────────────────────────────────────
  { id: 501, name: 'Bridal Long Haar 1',       category: 'Necklaces', description: 'Traditional Long Haar',       details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar1.jpg') },
  { id: 502, name: 'Bridal Long Haar 2',       category: 'Necklaces', description: 'Heavy Long Haar',             details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar2.jpg') },
  { id: 503, name: 'Bridal Long Haar 3',       category: 'Necklaces', description: 'Designer Long Haar',          details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar3.jpg') },
  { id: 504, name: 'Bridal Long Haar 4',       category: 'Necklaces', description: 'Royal Long Haar',             details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar4.jpg') },
  { id: 505, name: 'Bridal Long Haar 5',       category: 'Necklaces', description: 'Traditional Long Haar',       details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar5.jpg') },
  { id: 506, name: 'Bridal Long Haar 6',       category: 'Necklaces', description: 'Heavy Long Haar',             details: 'Exquisite bridal long necklace in 22K.',      icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/long haar6.jpg') },

  // ── CHOKERS ──────────────────────────────────────────────────────────────────
  { id: 601, name: 'Royal Choker 101',         category: 'Necklaces', description: 'Bridal Gold Choker',          details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Choker101.jpg') },
  { id: 602, name: 'Royal Choker 102',         category: 'Necklaces', description: 'Designer Gold Choker',        details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Choker102.jpg') },
  { id: 603, name: 'Royal Choker 103',         category: 'Necklaces', description: 'Heavy Gold Choker',           details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Choker103.jpg') },
  { id: 604, name: 'Royal Choker 104',         category: 'Necklaces', description: 'Classic Gold Choker',         details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/choker104.jpg') },
  { id: 605, name: 'Royal Choker 105',         category: 'Necklaces', description: 'Bridal Gold Choker',          details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/choker105.jpg') },
  { id: 606, name: 'Royal Choker 106',         category: 'Necklaces', description: 'Designer Gold Choker',        details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/choker106.jpg') },
  { id: 607, name: 'Royal Choker 107',         category: 'Necklaces', description: 'Classic Gold Choker',         details: 'Stunning close-fitting choker design.',       icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/choker107.jpg') },

  // ── JADAU NECKLACES ──────────────────────────────────────────────────────────
  { id: 701, name: 'Jadau Masterpiece 1',      category: 'Necklaces', description: 'Traditional Jadau Set',       details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace1.jpg') },
  { id: 702, name: 'Jadau Masterpiece 2',      category: 'Necklaces', description: 'Bridal Jadau Set',            details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace2.jpg') },
  { id: 703, name: 'Jadau Masterpiece 3',      category: 'Necklaces', description: 'Designer Jadau Set',          details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace3.jpg') },
  { id: 704, name: 'Jadau Masterpiece 4',      category: 'Necklaces', description: 'Heavy Jadau Set',             details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace4.jpg') },
  { id: 705, name: 'Jadau Masterpiece 5',      category: 'Necklaces', description: 'Traditional Jadau Set',       details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace5.jpg') },
  { id: 706, name: 'Jadau Masterpiece 6',      category: 'Necklaces', description: 'Bridal Jadau Set',            details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace6.jpg') },
  { id: 707, name: 'Jadau Masterpiece 7',      category: 'Necklaces', description: 'Designer Jadau Set',          details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace7.jpg') },
  { id: 708, name: 'Jadau Masterpiece 8',      category: 'Necklaces', description: 'Heavy Jadau Set',             details: 'Intricate Kundan and Jadau craftsmanship.',   icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/Jadau Necklace8.jpg') },

  // ── TURKISH NECKLACES ────────────────────────────────────────────────────────
  { id: 801, name: 'Turkish Design 1',         category: 'Necklaces', description: 'Modern Turkish Necklace',     details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace1.jpg') },
  { id: 802, name: 'Turkish Design 2',         category: 'Necklaces', description: 'Elegant Turkish Necklace',    details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace2.jpg') },
  { id: 803, name: 'Turkish Design 3',         category: 'Necklaces', description: 'Light Turkish Necklace',      details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace3.jpg') },
  { id: 804, name: 'Turkish Design 4',         category: 'Necklaces', description: 'Premium Turkish Necklace',    details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace4.jpg') },
  { id: 805, name: 'Turkish Design 5',         category: 'Necklaces', description: 'Modern Turkish Necklace',     details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace5.jpg') },
  { id: 806, name: 'Turkish Design 6',         category: 'Necklaces', description: 'Elegant Turkish Necklace',    details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace6.jpg') },
  { id: 807, name: 'Turkish Design 7',         category: 'Necklaces', description: 'Light Turkish Necklace',      details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace7.jpg') },
  { id: 808, name: 'Turkish Design 8',         category: 'Necklaces', description: 'Premium Turkish Necklace',    details: 'Contemporary Turkish design gold necklace.',  icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/turkish necklace8.jpg') },

  // ── SHORT NECKLACES ──────────────────────────────────────────────────────────
  { id: 901, name: 'Short Daily Necklace 1',   category: 'Necklaces', description: 'Daily Wear Necklace',         details: 'Perfect for everyday elegance.',              icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/short necklace1.jpg') },
  { id: 902, name: 'Short Daily Necklace 2',   category: 'Necklaces', description: 'Designer Short Necklace',     details: 'Perfect for everyday elegance.',              icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/short necklace2.jpg') },
  { id: 903, name: 'Short Daily Necklace 3',   category: 'Necklaces', description: 'Light Short Necklace',        details: 'Perfect for everyday elegance.',              icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/short necklace3.jpg') },
  { id: 904, name: 'Short Daily Necklace 4',   category: 'Necklaces', description: 'Premium Short Necklace',      details: 'Perfect for everyday elegance.',              icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/short necklace4.jpg') },
  { id: 905, name: 'Short Daily Necklace 5',   category: 'Necklaces', description: 'Daily Wear Necklace',         details: 'Perfect for everyday elegance.',              icon: 'flower-outline',  color: '#8C5C2D', image: require('../assets/short necklace5.jpg') },

  // ── EARRINGS ─────────────────────────────────────────────────────────────────
  { id: 1001, name: 'Gold Earring 101',        category: 'Earrings',  description: 'Classic Earring Set',         details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings101.jpg') },
  { id: 1002, name: 'Gold Earring 102',        category: 'Earrings',  description: 'Designer Earring Set',        details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings102.jpg') },
  { id: 1004, name: 'Gold Earring 104',        category: 'Earrings',  description: 'Heavy Earring Set',           details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings104.jpg') },
  { id: 1005, name: 'Gold Earring 105',        category: 'Earrings',  description: 'Classic Earring Set',         details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings105.jpg') },
  { id: 1006, name: 'Gold Earring 106',        category: 'Earrings',  description: 'Designer Earring Set',        details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings106.jpg') },
  { id: 1007, name: 'Gold Earring 107',        category: 'Earrings',  description: 'Heavy Earring Set',           details: 'Beautiful craftsmanship in 22K gold.',        icon: 'ellipse-outline', color: '#8C5C2D', image: require('../assets/earrings107.jpg') },

  // ── BANGLES ──────────────────────────────────────────────────────────────────
  { id: 1100, name: 'Classic Bangle 100',      category: 'Bracelets', description: 'Traditional Bangle Pair',     details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle100.jpg') },
  { id: 1101, name: 'Classic Bangle 101',      category: 'Bracelets', description: 'Designer Bangle Pair',        details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle101.jpg') },
  { id: 1102, name: 'Classic Bangle 102',      category: 'Bracelets', description: 'Heavy Bangle Pair',           details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle102.jpg') },
  { id: 1103, name: 'Classic Bangle 103',      category: 'Bracelets', description: 'Traditional Bangle Pair',     details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle103.jpg') },
  { id: 1104, name: 'Classic Bangle 104',      category: 'Bracelets', description: 'Designer Bangle Pair',        details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle104.jpg') },
  { id: 1105, name: 'Classic Bangle 105',      category: 'Bracelets', description: 'Heavy Bangle Pair',           details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle105.jpg') },
  { id: 1106, name: 'Classic Bangle 106',      category: 'Bracelets', description: 'Traditional Bangle Pair',     details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle106.jpg') },
  { id: 1107, name: 'Classic Bangle 107',      category: 'Bracelets', description: 'Designer Bangle Pair',        details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle107.jpg') },
  { id: 1108, name: 'Classic Bangle 108',      category: 'Bracelets', description: 'Heavy Bangle Pair',           details: 'Stunning traditional bangle set.',            icon: 'ellipse',         color: '#8C5C2D', image: require('../assets/bangle108.jpg') },
];
